# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8aad66ce2e17dc1f0c338427dd280bab9670f5ad153069ede4e66ae657ff06328bf00cb1c7b8a075db46207707f933970c547f07ab677531fde1bf46165200d
  s3_bucket: bookgraphs
  s3_access_key_id: AKIAINDFPYLGX72BJS5Q
  s3_access_key: +S0AF8EqcS/1SIRzq2FaRW4663K5gNieHTweLxvu
  s3_host_name: s3-eu-west-1.amazonaws.com

test:
  secret_key_base: db1f845ee1d68c55d1cc06eb3e0290e689944fa22a7ed46e380517a01313498261b9c71d82bc779ca91170324a237c2d6ff7060dc2d5127d4bc68b5d00822407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
